// API para obter o CEP
GET https://viacep.com.br/ws/69037000/json/
Content-Type: application/json
###
// API Usuário
// Inserir usuario
POST http://10.0.0.103:8080/user 
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "nome": "Marcio Amoedo",
    "login": "amoedo",
    "senha": "mypasswd",
    "email": "2023204776@ifam.edu.br"
 }
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

POST http://localhost:8080/user 
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "nome": "Benevaldo Pereira Goncalves",
    "login": "benevaldo",
    "senha": "7474",
    "email": "benevaldo@gmail.com"
 }
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###
// Listar todos os usuários em ordem alfabética do nome
GET http://10.0.0.103:8080/user/list 
Content-Type: application/json
###

// Obter usuário pelo ID
GET http://10.0.0.103:8080/user/18
Content-Type: application/json
###

// Alterar usuário pelo ID
// OBS: obrigado preencher o campo ID
PUT http://10.0.0.103:8080/user 
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "id": 18,
  "nome": "Marcio Amoedo da Silva",
  "login": "marcio.amoedo",
  "email": "marcio.mao.am@gmail.com",
  "senha": "1842"
}
###
// Obter usuário pelo ID
GET http://10.0.0.103:8080/user/41
Content-Type: application/json
###
// Deletar usuário pelo ID
DELETE http://10.0.0.103:8080/user/41
Content-Type: application/json
###
// Listar todos os usuários em ordem alfabética do nome
GET http://localhost:8080/user/list 
Content-Type: application/json
###
// Validar Usuário pelo Login e Senha
POST http://10.0.0.103:8080/user/validarLogin/marcio/12343
Content-Type: application/json
###

